"""empty message

Revision ID: d3d30115fc65
Revises: 
Create Date: 2026-03-20 13:05:27.108100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d30115fc65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('vehicle',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type_vehicle', sa.String(length=120), nullable=False),
    sa.Column('price_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['vehicle.car_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('media_vehicle',
    sa.Column('media_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('url_vehicle', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['vehicle.car_id'], ),
    sa.PrimaryKeyConstraint('media_vehicle_id')
    )
    op.create_table('post_spot',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone_formatted', sa.String(length=30), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_sleepable', sa.Boolean(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('has_waste_dump', sa.Boolean(), nullable=True),
    sa.Column('has_electricity', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('spot_id')
    )
    op.create_table('coment',
    sa.Column('coment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('coment_text', sa.String(length=450), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['post_spot.spot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('coment_id')
    )
    op.create_table('favorire_spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Spot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Spot_id'], ['post_spot.spot_id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_spot',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_spot.spot_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('review_van',
    sa.Column('review_van_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bookking_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('coment_review', sa.String(length=450), nullable=True),
    sa.Column('rating_review', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['vehicle.car_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('review_van_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_van')
    op.drop_table('media_spot')
    op.drop_table('favorire_spot')
    op.drop_table('coment')
    op.drop_table('post_spot')
    op.drop_table('media_vehicle')
    op.drop_table('booking')
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
